version: "3.9"
services:
  mongo:
    image: mongo:6
    container_name: museai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: museai
volumes:
  mongo_data:
